== Sagan: the spring.io site and reference application

==== Latest production deployment image:https://travis-ci.org/spring-io/sagan.svg?branch=master[Build Status,link=https://travis-ci.org/spring-io/sagan]

Welcome! The code in the master branch of this repository is deployed and running right now at http://spring.io[spring.io]. The http://spring.io/blog[blog], the collection of http://spring.io/guides[guides], and everything else you see there is implemented right here.

In addition to the practical purpose of powering Spring's home on the web, this project is designed to serve as a _reference application_–a resource that developers can use to see how the http://spring.io/team[Spring team] have used Spring to implement a real-world app with a few interesting requirements. We hope you'll find it useful!

== Getting started

You'll find everything you need to get started in the https://github.com/spring-io/sagan/wiki[project wiki], but you can also begin by simply browsing through the repository and finding what's of interest to you. You'll find README files in key directories, and Javadoc throughout the code. The app and all of its documentation are designed with the idea of a 'self-guided tour' in mind.

== Q&amp;A and issue tracking

If you have any questions, feedback, or feature requests, don't hesitate to https://github.com/spring-io/sagan/issues[add an issue].

== Contributing

http://help.github.com/send-pull-requests[Pull requests] are welcome; see the link:CONTRIBUTING.md[contributor guidelines] for details.

NOTE: To work on the code, you must format your code as well. For Eclipse users, see link:/style for format settings. For IntelliJ users, you need the Eclipse Formatter Plugin with the same files. This includes both style editing as well as import order settings.

== License

Sagan is released under the link:LICENSE.md[BSD-3 license].