-- Sample data for the blog

insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (1, 'This week in Spring - June 1, 2013',  'ENGINEERING',     false, false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-01 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (2, 'This week in Spring - June 2, 2013',  'ENGINEERING',     false, false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-02 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (3, 'This week in Spring - June 3, 2013',  'ENGINEERING',     false, false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-03 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (4, 'This week in Spring - June 4, 2013',  'ENGINEERING',     false, false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-04 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (5, 'This week in Spring - June 5, 2013',  'ENGINEERING',     false, false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-05 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (6, 'This week in Spring - June 6, 2013',  'ENGINEERING',     false, false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-06 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (7, 'This week in Spring - June 7, 2013',  'RELEASES',        false, false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-07 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (8, 'This week in Spring - June 8, 2013',  'RELEASES',        false, false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-08 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (9, 'This week in Spring - June 9, 2013',  'RELEASES',        false, false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-09 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (10, 'This week in Spring - June 10, 2013','NEWS_AND_EVENTS', false, false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-10 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (11, 'This week in Spring - June 11, 2013','NEWS_AND_EVENTS', false, false, 'raw', '<p>Welcome to another installment of This Week in Spring. The SpringOne2GX super early bird registration discount expires on June 10th, 2013, so make your arrangements now to secure the discount. Also, we&#8217;ve got three webinars coming up this month, check out the details below. As usual, we&#8217;ve got a lot to cover, so let&#8217;s get to it!</p>\n\n<ol>\n<li><p>I&#8217;ll be doing a webinar on building effective REST APIs with Spring on June 13th. I&#8217;ll be introducing Spring&#8217;s deep support for REST services, starting with Spring MVC and moving up the Richardson Maturity Model to incorporate Spring HATEOAS and, ultimately, Spring Data REST. Along the way we&#8217;ll look at the REST shell, and other concerns like security through OAuth.</p></li>\n<li><p>Join Jon Brisbin as he introduces Reactor in a webinar on June 18th. Reactor provides a foundational framework for applications that need high throughput when performing reasonably small chunks of stateless, asynchronous processing.</p></li>\n<li><p>Join Tony Erksine from Liberty University on June 27th as he instructs us How to talk Spring and Influence People, a pragmatic lesson on soft skills and technology adoption strategies needed to help get other developers in your company excited about,a nd using, new technology &#8212; in this case, with Spring.</p></li>\n<li><p>If you&#8217;re in the bay area, be sure to check out JAXConf happening right now in Santa Clara. Admission is free and there are some great speakers there. I will be speaking there tomorrow on Spring 4, and Multi Client Development with Spring, so feel free to drop by if you&#8217;d like to talk Spring, Cloud Foundry and big-data.</p></li>\n</ol>\n', '<p>Welcome to another installment of <strong>This Week in Spring</strong>. The SpringOne2GX super early bird registration discount expires on June 10th, 2013, so make your arrangements now to secure the discount. Also, we&#8217;ve got three webinars coming up this month, check out the details below. As usual, we&#8217;ve got a lot to cover, so let&#8217;s get to it!</p>', '2013-06-11 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (12, 'This week in Spring - June 12, 2013','NEWS_AND_EVENTS', false, false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-12 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (13, 'This week in Spring - June 12, 2013','ENGINEERING',     true,  false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-12 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (14, 'This week in Spring - June 12, 2013','ENGINEERING',     true,  false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-12 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (15, 'This week in Spring - June 12, 2013','RELEASES',        true,  false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-12 20:08:08');
insert into Post(id, title, category, broadcast, draft, rawContent, renderedContent, renderedSummary, createdDate) values (16, 'This week in Spring - June 12, 2013','NEWS_AND_EVENTS', true,  false, 'Test raw', 'Test rendered', 'Test Summary', '2013-06-12 20:08:08');
