---
applications:
- name: sagan-blue
  memory: 2G
  instances: 4
  env:
    GITHUB_CLIENT_ID: 42691b6b79a6387014ef
    SPRING_PROFILES_ACTIVE: production
    ELASTICSEARCH_INDEX: sagan-production
    NEW_RELIC_APP_NAME: sagan-blue;sagan
  host: sagan-production-blue
  domain: cfapps.io
  path: ../build/libs/sagan-site.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack
- name: sagan-green
  memory: 2G
  instances: 4
  env:
    GITHUB_CLIENT_ID: 42691b6b79a6387014ef
    SPRING_PROFILES_ACTIVE: production
    ELASTICSEARCH_INDEX: sagan-production
    NEW_RELIC_APP_NAME: sagan-green;sagan
  host: sagan-production-green
  domain: cfapps.io
  path: ../build/libs/sagan-site.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack
