resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: sagan-site-repo
  type: git
  icon: github-circle
  source:
    uri: "https://github.com/spring-io/sagan.git"
    ignore_paths: ["sagan-renderer/*"]
- name: sagan-renderer-repo
  type: git
  icon: github-circle
  source:
    uri: "https://github.com/spring-io/sagan.git"
    ignore_paths: ["sagan-site/*", "sagan-common/*"]
- name: sagan-cf-production
  type: cf
  icon: cloud
  source:
    api: https://api.run.pivotal.io
    username: ((sagan-cf-login))
    password: ((sagan-cf-password))
    organization: spring.io
    space: production
- name: slack-alert
  type: slack-notification
  icon: slack
  source:
    url: ((slack-webhook-url))

jobs:
- name: deploy-sagan-renderer
  serial: true
  plan:
  - get: sagan-renderer-repo
    trigger: true
    params: { submodules: none }
  - task: build-sagan-renderer
    file: sagan-renderer-repo/concourse/tasks/build-sagan-renderer.yml
    params:
  - put: sagan-cf-production
    params:
      current_app_name: sagan-renderer
      path: ./build/libs/sagan-renderer-1.0.0.BUILD-SNAPSHOT.jar
      environment_variables:
        SPRING_PROFILES_ACTIVE: production
        SAGAN_RENDERER_GITHUB_TOKEN: ((sagan-github-access-token))
      manifest: sagan-renderer-repo/concourse/manifests/sagan-renderer-production.yml
  - put: slack-alert
    params:
      text: ":concourse-succeeded: <https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|${BUILD_PIPELINE_NAME} ${BUILD_JOB_NAME} was successful!>"
      silent: true
      icon_emoji: ":concourse:"
      username: concourse-ci
- name: deploy-sagan-site
  serial: true
  plan:
  - get: sagan-site-repo
    trigger: true
    params: { submodules: none }
  - task: build-sagan-site
    file: sagan-site-repo/concourse/tasks/build-sagan-site.yml
    params:
      # JSPM github authentication is needed for the CI
      # otherwise install steps reach github API limitation
      JSPM_GITHUB_AUTH_TOKEN: ((jspm-github-auth-token))
  - put: sagan-cf-production
    params:
      current_app_name: sagan
      path: ./build/libs/sagan-site-1.0.0.BUILD-SNAPSHOT.jar
      environment_variables:
        SPRING_PROFILES_ACTIVE: production
        ELASTICSEARCH_INDEX: sagan-production
        ADMIN_PASSWORD: ((sagan-admin-password))
        GITHUB_CLIENT_ID: ((sagan-github-clientid))
        GITHUB_CLIENT_SECRET: ((sagan-github-clientsecret))
        GITHUB_ACCESS_TOKEN: ((sagan-github-access-token))
        WEBHOOK_ACCESS_TOKEN: ((sagan-webhook-access-token))
      manifest: sagan-site-repo/concourse/manifests/sagan-site-production.yml
  - put: slack-alert
    params:
      text: ":concourse-succeeded: <https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|${BUILD_PIPELINE_NAME} ${BUILD_JOB_NAME} was successful!>"
      silent: true
      icon_emoji: ":concourse:"
      username: concourse-ci
groups:
- name: Deploy
  jobs:
  - deploy-sagan-renderer
  - deploy-sagan-site
